=== vazlat/vazlat.github.io/VKR/xml/Sceme.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">

    <xs:element name="dataBase">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="measurement">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="metering" type="meteringInfo" maxOccurs="unbounded"></xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="consts">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="const" type="constsInfo" maxOccurs="unbounded"></xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="meteringInfo">
    <xs:sequence>
        <xs:element name="type" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="unit" type="xs:string"/>
        <xs:element name="value" type="xs:decimal"/>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="time" type="xs:time"/>
    </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constsInfo">
    <xs:sequence>
        <xs:element name="type" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="unit" type="xs:string"/>
        <xs:element name="cold">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="optimal" type="minMax" maxOccurs="1"></xs:element>
                <xs:element name="permissible" type="minMax" maxOccurs="1"></xs:element>
            </xs:sequence>
            </xs:complexType>
        </xs:element>
        <xs:element name="warm">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="optimal" type="minMax" maxOccurs="1"></xs:element>
                <xs:element name="permissible" type="minMax" maxOccurs="1"></xs:element>
            </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    </xs:complexType>

    <xs:complexType name="minMax">
    <xs:sequence>
        <xs:element name="min" type="xs:decimal"/>
        <xs:element name="max" type="xs:decimal"/>
    </xs:sequence>
    </xs:complexType>
</xs:schema>

=== vazlat/vazlat.github.io/VKR/xml/Database.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataBase
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Sceme.xsd">
    <measurement>
        <metering>
            <type>Microclimate</type>
            <title>Air temperature</title>
            <unit>&#8304;C</unit>
            <value>18.0</value>
            <date>2020-05-11</date>
            <time>10:40:00</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Air temperature</title>
            <unit>&#8304;C</unit>
            <value>24.0</value>
            <date>2020-05-11</date>
            <time>10:50:00</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Air temperature</title>
            <unit>&#8304;C</unit>
            <value>29.0</value>
            <date>2020-05-11</date>
            <time>11:00:00</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Surface temperature</title>
            <unit>&#8304;C</unit>
            <value>16</value>
            <date>2020-05-11</date>
            <time>10:40:02</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Surface temperature</title>
            <unit>&#8304;C</unit>
            <value>26.0</value>
            <date>2020-05-11</date>
            <time>10:50:02</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Surface temperature</title>
            <unit>&#8304;C</unit>
            <value>29.0</value>
            <date>2020-05-11</date>
            <time>11:00:02</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Relative humidity</title>
            <unit>%</unit>
            <value>10</value>
            <date>2020-05-11</date>
            <time>10:40:03</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Relative humidity</title>
            <unit>%</unit>
            <value>50</value>
            <date>2020-05-11</date>
            <time>10:50:03</time>
        </metering>
        <metering>
            <type>Microclimate</type>
            <title>Relative humidity</title>
            <unit>%</unit>
            <value>70</value>
            <date>2020-05-11</date>
            <time>11:00:03</time>
        </metering>
        <metering>
            <type>Production factors</type>
            <title>Noise</title>
            <unit>db</unit>
            <value>25</value>
            <date>2020-05-11</date>
            <time>10:40:05</time>
        </metering>
        <metering>
            <type>Production factors</type>
            <title>Noise</title>
            <unit>db</unit>
            <value>56</value>
            <date>2020-05-11</date>
            <time>10:50:05</time>
        </metering>
        <metering>
            <type>Production factors</type>
            <title>Illumination</title>
            <unit>lx</unit>
            <value>100</value>
            <date>2020-05-11</date>
            <time>10:40:07</time>
        </metering>
        <metering>
            <type>Production factors</type>
            <title>Illumination</title>
            <unit>lx</unit>
            <value>350</value>
            <date>2020-05-11</date>
            <time>10:50:07</time>
        </metering>
        <metering>
            <type>Production factors</type>
            <title>Illumination</title>
            <unit>lx</unit>
            <value>510</value>
            <date>2020-05-11</date>
            <time>11:00:07</time>
        </metering>
    </measurement>
    <consts>
        <const>
            <type>Microclimate</type>
            <title>Air temperature</title>
            <unit>&#8304;C</unit>
            <cold>
                <optimal>
                    <min>22.0</min>
                    <max>24.0</max>
                </optimal>
                <permissible>
                    <min>20.0</min>
                    <max>25.0</max>
                </permissible>
            </cold>
            <warm>
                <optimal>
                    <min>23.0</min>
                    <max>25.0</max>
                </optimal>
                <permissible>
                    <min>21.0</min>
                    <max>28.0</max>
                </permissible>
            </warm>
        </const>
        <const>
            <type>Microclimate</type>
            <title>Surface temperature</title>
            <unit>&#8304;C</unit>
            <cold>
                <optimal>
                    <min>21.0</min>
                    <max>25.0</max>
                </optimal>
                <permissible>
                    <min>19.0</min>
                    <max>26.0</max>
                </permissible>
            </cold>
            <warm>
                <optimal>
                    <min>22.0</min>
                    <max>26.0</max>
                </optimal>
                <permissible>
                    <min>20.0</min>
                    <max>29.0</max>
                </permissible>
            </warm>
        </const>
        <const>
            <type>Microclimate</type>
            <title>Relative humidity</title>
            <unit>%</unit>
            <cold>
                <optimal>
                    <min>40</min>
                    <max>60</max>
                </optimal>
                <permissible>
                    <min>15</min>
                    <max>75</max>
                </permissible>
            </cold>
            <warm>
                <optimal>
                    <min>40</min>
                    <max>60</max>
                </optimal>
                <permissible>
                    <min>15</min>
                    <max>75</max>
                </permissible>
            </warm>
        </const>
        <const>
            <type>Production factors</type>
            <title>Noise</title>
            <unit>db</unit>
            <cold>
                <optimal>
                    <min>0</min>
                    <max>55</max>
                </optimal>
                <permissible>
                    <min>0</min>
                    <max>55</max>
                </permissible>
            </cold>
            <warm>
                <optimal>
                    <min>0</min>
                    <max>55</max>
                </optimal>
                <permissible>
                    <min>0</min>
                    <max>55</max>
                </permissible>
            </warm>
        </const>
        <const>
            <type>Production factors</type>
            <title>Illumination</title>
            <unit>lx</unit>
            <cold>
                <optimal>
                    <min>300</min>
                    <max>500</max>
                </optimal>
                <permissible>
                    <min>300</min>
                    <max>500</max>
                </permissible>
            </cold>
            <warm>
                <optimal>
                    <min>300</min>
                    <max>500</max>
                </optimal>
                <permissible>
                    <min>300</min>
                    <max>500</max>
                </permissible>
            </warm>
        </const>
    </consts>
</dataBase>
